INPUT:
  PIXEL_MEAN: [0., 0., 0.]
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "ImageNet-Pretrain-models/COCO_FPN_300M_supernet.pkl"
  BACKBONE:
    CONV_BODY: "DETNAS-COCO-FPN-300M-search"
    CHANNEL_SHUFFLE_METHOD: 1
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  FPN:
    USE_SYNCBN: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPNXconv1fcFeatureExtractor"
    USE_SYNCBN: True
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("coco_2014_trainval_train",)
  TEST: ("coco_2014_trainval_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
